baseURL = "https://otterable4.github.io/"
paginate = 9
theme = 'maverick'
#-------------------------------
defaultContentLanguage = 'en'
[languages]
  [languages.en]
     title = "Femboy.at"
  [languages.de]
     title = "Ermine.de"






# Main Menu


[params]
  logo = "/images/ottor2.png" # Yoiu can add own logo. For example "/images/logo.png".
  description = "Aditu is a stylish and modern dark theme with a clean and unique design."

# Google Analytics 4
googleAnalyticsID = "G-CJN754RWRH"

  #-------------------------------
  # Hero Settings
  [params.hero]

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false